import { z } from "zod";

// Define the Staff schema using Zod for frontend validation
export const staffSchema = z.object({
  id: z.number().optional(), // Optional as ID is generated by the backend
  name: z.string().min(2, "Name is required"),
  email: z.string().email("Invalid email address"),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters long")
    .regex(
      /(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$%^&*])/,
      "Password must contain a letter, a number, and a special character"
    ),
  address: z.string().optional(),
  profile_image: z.string().url("Profile image must be a valid URL").optional(),
  role: z.string().min(2, "Role is required"),
  roomId: z.number().optional(), // Optional room ID
});

export type Staff = z.infer<typeof staffSchema>;
